name: Publish Docker Image to GHCR on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        run: | 
          docker build -t ghcr.io/${{ github.repository | toLower }}/knock-knock:${{ github.event.release.tag_name }} \
                       -t ghcr.io/${{ github.repository | toLower }}/knock-knock:latest .

      - name: Push Docker Image
        run: | 
          docker push ghcr.io/${{ github.repository | toLower }}/knock-knock:${{ github.event.release.tag_name }}
          docker push ghcr.io/${{ github.repository | toLower }}/knock-knock:latest