name: Build Dev Docker Image

on:
  push:
    branches:
      - dev  # or your test branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tag
        run: |
          echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: | 
          docker build -t ghcr.io/${{ github.repository | toLower }}/knock-knock:${{ env.TAG }} \
                       -t ghcr.io/${{ github.repository | toLower }}/knock-knock:dev .

      - name: Push Docker Image
        run: | 
          docker push ghcr.io/${{ github.repository | toLower }}/knock-knock:${{ env.TAG }}
          docker push ghcr.io/${{ github.repository | toLower }}/knock-knock:dev
